version: "3.3"
services:

  backend-server:
    image: registry.gitlab.com/librefoodpantry/client-solutions/theas-pantry/guestinfosystem/guestinfobackend:jsdoc
    ports:
      - 3000:3000
    environment:
      HOST_BASE_URL: http://localhost:3000
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network

networks:
  backend-network:
