version: "3.3"
services:

  backend-database:
    image: mongo:4
    ports:
      - "27018:27018"
    networks:
      - backend-network
    environment:
      MONGO_INITDB_DATABASE: backend-database
    command: mongod --port 27018

# https://docs.docker.com/compose/compose-file/
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      # The location of the RabbitMQ server.  "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      -  backend-network

networks:
  backend-network:

