openapi: 3.0.3


info:
  title: GuestInfoBackend
  version: 0.1.0

servers:
  # This is overriden by HOST_BASE_URL.
  - url: http://localhost:10001/v0

paths:
  /guest-info/{studentID}:
    description: For info about the guest with given id.
    parameters:
      - in: path
        name: studentID
        schmea:
          $ref: '#/components/schemas/studentID'
        required: true
        description: Student ID of the guest whose info is desired.

    get:
      description: Gets guest's data.
      x-eov-operation-handler: endpoints
      operationId: getGuestData
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Guest'
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'

    put:
      description: Modifies guest's data.
      x-eov-operation-handler: endpoints
      operationId: updateGuestData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Guest'
            description: Successful modification.
            headers:
              Location:
                description: URI of item.
                explode: false
                required: true
                schema:
                  minLenght: 1
                  nullable: false
                  type: string
                style: simple
        "400":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/ServerError'

components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EovError'
    BadRequest:
      description: The request was malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EovError'
    ServerError:
      description: There was an error in the server
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EovError'
  schemas:

    Guest:
      type: object
      properties:
        studentID:
          $ref: '#/components/schemas/studentID'
        residency:
          $ref: '#/components/schemas/residency'
        zipCode:
          $ref: '#/components/schemas/zipCode'
        householdSize:
          $ref: '#/components/schemas/householdSize'
        ageRange:
          $ref: '#/components/schemas/ageRange'
        employmentStatus:
          $ref: '#/components/schemas/employmentStatus'
        special:
          $ref: '#/components/schemas/special'
        SNAP:
          $ref: '#/components/schemas/SNAP'
      required:
        - studentID
        - residency
        - zipCode
        - householdSize
        - ageRange
        - employmentStatus
        - special
        - SNAP

    studentID:
      description: Unique student identifier
      nullable: false
      pattern: ^\d{7}$
      type: string

    residency:
      description: whether the student lives on campus or not
      nullable: false
      pattern: \S+
      type: string

    zipCode:
      description: student zip code (01602 if resident)
      nullable: false
      pattern: ^\d{5}(?:[-\s]\d{4})?$
      type: string

    householdSize:
      description: size of student's household
      nullable: false
      type: integer
      minimum: 0
      maximum: 6

    ageRange:
      description: student age (in a range)
      nullable: false
      type: string

    employmentStatus:
      description: employed or unemployed
      nullable: false
      type: string

    special:
      description: the kind of aid that the student recieves; or none
      nullable: false
      type: array
      items:
        $ref: '#/components/schemas/specialCases'

    specialCases:
      description: each case of aid the student recieves
      type: string

    SNAP:
      description: whether or not the student would like assistance applying for SNAP
      nullable: false
      type: string

    EovError:
      description: Not Acceptable
      type: object
      example: {
        "message": ".response should have required property 'name', .response should have required property 'id'",
        "errors": [
          {
            "path": ".response.name",
            "message": "should have required property 'name'",
            "errorCode": "required.openapi.validation"
          },
          {
            "path": ".response.id",
            "message": "should have required property 'id'",
            "errorCode": "required.openapi.validation"
          }
        ]
      }
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
              message:
                type: string
              errorCode:
                type: "string"
